//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelFileInspector.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelFileInspector.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ExcelFileInspector に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査ファイルクリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearInspectionFile {
            get {
                return ResourceManager.GetString("ClearInspectionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査実施 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteInspection {
            get {
                return ResourceManager.GetString("ExecuteInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重要なお知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionFile {
            get {
                return ResourceManager.GetString("InspectionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionMethod {
            get {
                return ResourceManager.GetString("InspectionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionResult {
            get {
                return ResourceManager.GetString("InspectionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionSettings {
            get {
                return ResourceManager.GetString("InspectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました｡
        ///このアプリケーションを終了します｡
        ///エラーの詳細な情報を表示しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査したいファイル　もしくは　検査したいファイルが含まれるフォルダを
        ///ドラッグ&amp;ドロップしてください｡
        ///対象ファイルキーワードを含むファイルのみ検査ファイルに登録されます｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageGuideDragAndDrop {
            get {
                return ResourceManager.GetString("MessageGuideDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションのプロジェクトURLを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageOpenProjectUrl {
            get {
                return ResourceManager.GetString("MessageOpenProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGEmpty {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が&quot;{0}&quot;になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGEqual {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄以外になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGNotEmpty {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が&quot;{0}&quot;以外になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGNotEqual {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題は見つかりませんでした｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionOK {
            get {
                return ResourceManager.GetString("MessageResultInspectionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備が完了しました｡｢検査実施｣ボタン押下で検査を行います｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusAlreadyInspection {
            get {
                return ResourceManager.GetString("MessageStatusAlreadyInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteInspection {
            get {
                return ResourceManager.GetString("MessageStatusCompleteInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査ファイルが指定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusInspectionFileEmpty {
            get {
                return ResourceManager.GetString("MessageStatusInspectionFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査方法が設定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusInspectionMethodEmpty {
            get {
                return ResourceManager.GetString("MessageStatusInspectionMethodEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査を行っています｡({0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusNowInspection {
            get {
                return ResourceManager.GetString("MessageStatusNowInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シート名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ファイルキーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetFileKeyword {
            get {
                return ResourceManager.GetString("TargetFileKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
